In [6]:
import pandas as pd
match = pd.read_csv("../data/raw/MatchTbl.csv")

In [7]:
match.head()

           MatchId           Patch QueueType  RankFk  GameDuration
0  EUN1_3707659547  14.23.636.9832      ARAM       0          1173
1  EUN1_3709211408  14.24.642.1879   CLASSIC       0          1986
2  EUN1_3710823249  14.24.643.5128      ARAM       0           813
3  EUN1_3710849604  14.24.643.5128      ARAM       0          1070
4  EUN1_3710885279  14.24.643.5128      ARAM       0           968

In [8]:
match.info()

<class 'pandas.DataFrame'>
RangeIndex: 279423 entries, 0 to 279422
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   MatchId       279423 non-null  str
 1   Patch         279387 non-null  str
 2   QueueType     279387 non-null  str
 3   RankFk        279423 non-null  int64
 4   GameDuration  279423 non-null  int64
dtypes: int64(2), str(3)
memory usage: 10.7 MB

In [9]:
stats = pd.read_csv("../data/raw/MatchStatsTbl.csv")

stats.info()

<class 'pandas.DataFrame'>
RangeIndex: 732308 entries, 0 to 732307
Data columns (total 31 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   MatchStatsId          732308 non-null  int64
 1   SummonerMatchFk       732308 non-null  int64
 2   MinionsKilled         732308 non-null  int64
 3   DmgDealt              732308 non-null  int64
 4   DmgTaken              732308 non-null  int64
 5   TurretDmgDealt        732308 non-null  int64
 6   TotalGold             732308 non-null  int64
 7   Lane                  554999 non-null  str
 8   Win                   732308 non-null  int64
 9   item1                 732308 non-null  int64
 10  item2                 732308 non-null  int64
 11  item3                 732308 non-null  int64
 12  item4                 732308 non-null  int64
 13  item5                 732308 non-null  int64
 14  item6                 732308 non-null  int64
 15  kills                 732308 non-null  int64
 16  deaths                732308 non-null  int64
 17  assists               732308 non-null  int64
 18  PrimaryKeyStone       732308 non-null  int64
 19  PrimarySlot1          732308 non-null  int64
 20  PrimarySlot2          732308 non-null  int64
 21  PrimarySlot3          732308 non-null  int64
 22  SecondarySlot1        732308 non-null  int64
 23  SecondarySlot2        732308 non-null  int64
 24  SummonerSpell1        732308 non-null  int64
 25  SummonerSpell2        732308 non-null  int64
 26  CurrentMasteryPoints  732308 non-null  int64
 27  EnemyChampionFk       732308 non-null  int64
 28  DragonKills           732308 non-null  int64
 29  BaronKills            732308 non-null  int64
 30  visionScore           732308 non-null  int64
dtypes: int64(30), str(1)
memory usage: 173.2 MB

In [10]:
champion = pd.read_csv("../data/raw/ChampionTbl.csv")

champion.head()

   ChampionId ChampionName
0           0  No Champion
1           1        Annie
2           2         Olaf
3           3        Galio
4           4  TwistedFate

In [11]:
champion.info()

<class 'pandas.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ChampionId    173 non-null    int64
 1   ChampionName  173 non-null    str
dtypes: int64(1), str(1)
memory usage: 2.8 KB

In [12]:
summoner = pd.read_csv("../data/raw/SummonerMatchTbl.csv")

summoner.head()

   SummonerMatchId  SummonerFk          MatchFk  ChampionFk
0                1           1  EUW1_7565751492         902
1                2           1  EUW1_7565549583         902
2                3           1  EUW1_7564803077          16
3                4           1  EUW1_7564368646         103
4                5           1  EUW1_7564332041         800

In [13]:
summoner.info()

<class 'pandas.DataFrame'>
RangeIndex: 707832 entries, 0 to 707831
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SummonerMatchId  707832 non-null  int64
 1   SummonerFk       707832 non-null  int64
 2   MatchFk          707832 non-null  str
 3   ChampionFk       707832 non-null  int64
dtypes: int64(3), str(1)
memory usage: 21.6 MB

In [14]:
team = pd.read_csv("../data/raw/TeamMatchTbl.csv")

team.head()

,TeamID,MatchFk,B1Champ,B2Champ,B3Champ,B4Champ,B5Champ,R1Champ,R2Champ,R3Champ,...,BlueDragonKills,BlueTowerKills,BlueKills,RedBaronKills,RedRiftHeraldKills,RedDragonKills,RedTowerKills,RedKills,RedWin,BlueWin
0,1,EUW1_7565751492,897,154,157,51,902,164,5,25,...,1,3,13,1,0,3,8,26,1,0
1,2,EUW1_7565549583,82,238,157,236,89,6,254,127,...,3,10,39,0,1,1,3,33,0,1
2,3,EUW1_7564803077,516,28,4,498,235,23,64,38,...,2,7,27,2,0,3,8,37,1,0
3,4,EUW1_7564368646,54,34,59,498,103,61,25,55,...,0,4,55,0,0,0,0,39,0,1
4,5,EUW1_7564332041,12,800,111,150,142,141,101,55,...,0,0,42,0,0,0,0,0,0,1

In [15]:
team.info()

<class 'pandas.DataFrame'>
RangeIndex: 214330 entries, 0 to 214329
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   TeamID               214330 non-null  int64
 1   MatchFk              214330 non-null  str
 2   B1Champ              214330 non-null  int64
 3   B2Champ              214330 non-null  int64
 4   B3Champ              214330 non-null  int64
 5   B4Champ              214330 non-null  int64
 6   B5Champ              214330 non-null  int64
 7   R1Champ              214330 non-null  int64
 8   R2Champ              214330 non-null  int64
 9   R3Champ              214330 non-null  int64
 10  R4Champ              214330 non-null  int64
 11  R5Champ              214330 non-null  int64
 12  BlueBaronKills       214330 non-null  int64
 13  BlueRiftHeraldKills  214330 non-null  int64
 14  BlueDragonKills      214330 non-null  int64
 15  BlueTowerKills       214330 non-null  int64
 16  BlueKills            214330 non-null  int64
 17  RedBaronKills        214330 non-null  int64
 18  RedRiftHeraldKills   214330 non-null  int64
 19  RedDragonKills       214330 non-null  int64
 20  RedTowerKills        214330 non-null  int64
 21  RedKills             214330 non-null  int64
 22  RedWin               214330 non-null  int64
 23  BlueWin              214330 non-null  int64
dtypes: int64(23), str(1)
memory usage: 39.2 MB

In [16]:
stats.head()

,MatchStatsId,SummonerMatchFk,MinionsKilled,DmgDealt,DmgTaken,TurretDmgDealt,TotalGold,Lane,Win,item1,...,PrimarySlot3,SecondarySlot1,SecondarySlot2,SummonerSpell1,SummonerSpell2,CurrentMasteryPoints,EnemyChampionFk,DragonKills,BaronKills,visionScore
0,1,1,30,4765,12541,0,7058,BOTTOM,0,3870,...,8453,8345,8347,4,7,902,51,0,0,67
1,2,2,29,8821,14534,1,9618,BOTTOM,0,3870,...,8453,8345,8347,4,7,902,236,0,0,88
2,3,3,34,6410,19011,3,9877,BOTTOM,1,3870,...,8237,8345,8347,4,7,16,498,0,0,97
3,4,4,51,22206,14771,3,12374,NONE,1,6655,...,8106,8226,8210,4,14,103,54,0,0,0
4,5,5,0,39106,33572,0,15012,TOP,1,4015,...,0,0,0,2202,2201,800,12,0,0,0