# 04. Feature Engineering

## 📌 목표

추천 알고리즘에서 사용할 데이터셋을 생성한다.

### 진행 내용

- TeamMatchTbl 불러오기
- Champion ID → Champion Name 변환
- Blue Team 데이터 생성
- Red Team 데이터 생성
- 하나의 Team Dataset 생성

In [2]:
import pandas as pd

# 데이터 불러오기
team = pd.read_csv("../data/raw/TeamMatchTbl.csv")
champion = pd.read_csv("../data/raw/ChampionTbl.csv")

In [3]:
# Champion ID → Champion Name 변환
champion_dict = dict(zip(champion["ChampionId"], champion["ChampionName"]))

for col in [
    "B1Champ","B2Champ","B3Champ","B4Champ","B5Champ",
    "R1Champ","R2Champ","R3Champ","R4Champ","R5Champ"
]:
    team[col] = team[col].map(champion_dict)

In [4]:
team.head()

,TeamID,MatchFk,B1Champ,B2Champ,B3Champ,B4Champ,B5Champ,R1Champ,R2Champ,R3Champ,...,BlueDragonKills,BlueTowerKills,BlueKills,RedBaronKills,RedRiftHeraldKills,RedDragonKills,RedTowerKills,RedKills,RedWin,BlueWin
0,1,EUW1_7565751492,KSante,Zac,Yasuo,Caitlyn,Milio,Camille,XinZhao,Morgana,...,1,3,13,1,0,3,8,26,1,0
1,2,EUW1_7565549583,Mordekaiser,Zed,Yasuo,Lucian,Leona,Urgot,Vi,Lissandra,...,3,10,39,0,1,1,3,33,0,1
2,3,EUW1_7564803077,Ornn,Evelynn,TwistedFate,Xayah,Senna,Tryndamere,LeeSin,Kassadin,...,2,7,27,2,0,3,8,37,1,0
3,4,EUW1_7564368646,Malphite,Anivia,JarvanIV,Xayah,Ahri,Orianna,Morgana,Katarina,...,0,4,55,0,0,0,0,39,0,1
4,5,EUW1_7564332041,Alistar,Mel,Nautilus,Gnar,Zoe,Kayn,Xerath,Katarina,...,0,0,42,0,0,0,0,0,0,1

### 결과

모든 챔피언 ID를 실제 챔피언 이름으로 변환하였다.

In [5]:
blue_team = team[
    ["B1Champ","B2Champ","B3Champ","B4Champ","B5Champ","BlueWin"]
].copy()

In [6]:
blue_team.columns = [
    "Champ1",
    "Champ2",
    "Champ3",
    "Champ4",
    "Champ5",
    "Win"
]

In [7]:
red_team = team[
    ["R1Champ","R2Champ","R3Champ","R4Champ","R5Champ","RedWin"]
].copy()

In [8]:
red_team.columns = [
    "Champ1",
    "Champ2",
    "Champ3",
    "Champ4",
    "Champ5",
    "Win"
]

두 데이터 합치기 -> concat

In [9]:
team_dataset = pd.concat(
    [blue_team, red_team],
    ignore_index=True
)

In [10]:
team_dataset.head()

        Champ1   Champ2       Champ3   Champ4 Champ5  Win
0       KSante      Zac        Yasuo  Caitlyn  Milio    0
1  Mordekaiser      Zed        Yasuo   Lucian  Leona    1
2         Ornn  Evelynn  TwistedFate    Xayah  Senna    0
3     Malphite   Anivia     JarvanIV    Xayah   Ahri    1
4      Alistar      Mel     Nautilus     Gnar    Zoe    1

팀 조합을 하나의 문자열로 만들기

In [11]:
team_dataset["TeamComp"] = team_dataset[
    ["Champ1", "Champ2", "Champ3", "Champ4", "Champ5"]
].apply(lambda x: ",".join(sorted(x)), axis=1)